const phones = [
    {
        name: "Apple iPhone 17 Pro",
        id: "AI17P",
        color: "Naranja cósmico",
        image: "img/apple-iphone-17-pro-max-5g-dual-sim-256gb-12gb-ram-cosmic-orange.jpg",
        brand: "iPhone",
        screenSize: '16 cm / 6.3"',
        storage: "256 GB",
        os: "iOS",
        processor: "Chip A19 Pro",
        price: 1319,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 28/10/2025",
        pickup: "Consultar disponibilidad",
        description: 'OLED Super Retina XDR, 5G, 6.3", Chip A19 Pro, diseño elegante y rendimiento superior.'
    },
    {
        name: "Samsung Galaxy S25 Ultra",
        id: "SGS25U",
        color: "Titanium Grey",
        image: "img/samsung-galaxy-s25-ultra-5g-dual-sim-1-tb-12gb-ram-titanium-grey.jpg",
        brand: "Samsung",
        screenSize: '17 cm / 6.8"',
        storage: "1 TB",
        os: "Android 14",
        processor: "Snapdragon 8 Gen 4",
        price: 1349,
        discounted: true,
        oldPrice: 1499,
        availability: "Disponible online",
        delivery: "Entrega 30/10/2025",
        pickup: "Recogida en tienda disponible",
        description: "Pantalla Dynamic AMOLED 2X, cámara de 200 MP y gran autonomía."
    },
    {
        name: "Samsung Galaxy Z Fold 6",
        id: "SGZF6",
        color: "Ice Blue",
        image: "img/samsung-galaxy-z-fold5-5g-dual-esim-256gb-12gb-ram-sm-f946-ice-blue.jpg",
        brand: "Samsung",
        screenSize: '19 cm / 7.6"',
        storage: "256 GB",
        os: "Android 14",
        processor: "Snapdragon 8 Gen 3",
        price: 1849,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 01/11/2025",
        pickup: "Consultar disponibilidad",
        description: "Diseño plegable premium con pantalla AMOLED y rendimiento profesional."
    },
    {
        name: "Google Pixel 10 Pro",
        id: "GP10P",
        color: "Moonstone Grey",
        image: "img/google-pixel-10-pro-5g-dual-sim-256gb-16gb-ram-moonstone-grey.jpg",
        brand: "Google",
        screenSize: '16 cm / 6.3"',
        storage: "256 GB",
        os: "Android 15",
        processor: "Google Tensor G4",
        price: 1199,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 29/10/2025",
        pickup: "Recogida en tienda disponible",
        description: "Fotografía impulsada por IA, diseño elegante y actualizaciones garantizadas."
    },
    {
        name: "Xiaomi 14 Pro",
        id: "X14P",
        color: "Pearl White",
        image: "img/xiaomi14.jpg",
        brand: "Xiaomi",
        screenSize: '16.5 cm / 6.5"',
        storage: "512 GB",
        os: "Android 14 (HyperOS)",
        processor: "Snapdragon 8 Gen 3",
        price: 999,
        discounted: true,
        oldPrice: 1099,
        availability: "Disponible online",
        delivery: "Entrega 02/11/2025",
        pickup: "Consultar disponibilidad",
        description: "Rendimiento de gama alta con cámaras Leica y batería duradera."
    },
    {
        name: "Redmi 15T Pro",
        id: "R15P",
        color: "Rose Gold",
        image: "img/xiaomi-15t-5g-dual-sim-512gb-12gb-ram-rose-gold.jpg",
        brand: "Xiaomi",
        screenSize: '16 cm / 6.3"',
        storage: "512 GB",
        os: "Android 14 (HyperOS)",
        processor: "Dimensity 8300-Ultra",
        price: 529,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 03/11/2025",
        pickup: "Consultar disponibilidad",
        description: "Rápido, elegante y con batería de larga duración."
    },
    {
        name: "Oppo A5X",
        id: "OA5X",
        color: "Black Blue",
        image: "img/oppo-a5x-dual-sim-128gb-4gb-ram-black-blue.jpg",
        brand: "Oppo",
        screenSize: '16 cm / 6.3"',
        storage: "128 GB",
        os: "Android 14",
        processor: "MediaTek Helio G88",
        price: 229,
        discounted: true,
        oldPrice: 279,
        availability: "Disponible online",
        delivery: "Entrega 27/10/2025",
        pickup: "Recogida en tienda disponible",
        description: "Smartphone económico con gran batería y cámara doble de 50 MP."
    },
    {
        name: "Oppo Reno 11",
        id: "OR11",
        color: "Champagne Gold",
        image: "img/opporeno14.jpg",
        brand: "Oppo",
        screenSize: '16.5 cm / 6.5"',
        storage: "256 GB",
        os: "Android 14",
        processor: "Snapdragon 7s Gen 2",
        price: 649,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 28/10/2025",
        pickup: "Consultar disponibilidad",
        description: "Cámara avanzada y diseño elegante con acabado premium."
    },
    {
        name: "Google Pixel 9",
        id: "GP9",
        color: "Pink",
        image: "img/google-pixel-9-5g-dual-sim-256gb-12gb-ram-pink.jpg",
        brand: "Google",
        screenSize: '15.8 cm / 6.2"',
        storage: "256 GB",
        os: "Android 14",
        processor: "Google Tensor G3",
        price: 899,
        discounted: true,
        oldPrice: 999,
        availability: "Disponible online",
        delivery: "Entrega 29/10/2025",
        pickup: "Consultar disponibilidad",
        description: "Rendimiento fluido y fotografía espectacular impulsada por IA."
    },
    {
        name: "Oppo A5 Pro",
        id: "OAP",
        color: "Black Brown",
        image: "img/oppo-a5-pro-5g-dual-sim-256gb-8gb-ram-black-brown.jpg",
        brand: "Oppo",
        screenSize: '16 cm / 6.3"',
        storage: "256 GB",
        os: "Android 14",
        processor: "MediaTek Dimensity 7200",
        price: 499,
        discounted: false,
        availability: "Disponible online",
        delivery: "Entrega 30/10/2025",
        pickup: "Recogida en tienda disponible",
        description: "Pantalla AMOLED con excelente brillo y gran autonomía."
    }
];